base_url: /
simple_copy:
  - media/*
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.

plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.meta.AutoExtendPlugin
  - hyde.ext.plugins.text.SyntextPlugin
  - hyde.ext.plugins.text.TextlinksPlugin
  - hyde.ext.plugins.urls.UrlCleanerPlugin
  - hyde.ext.plugins.meta.SorterPlugin
  - hyde.ext.plugins.meta.TaggerPlugin
  - hyde.ext.plugins.structure.PaginatorPlugin

syntax:
  use_figure: False

sorter:
  name:
    attr: name
    filters:
      source_file.kind: html
      is_processable: True
  time:
     attr: meta.created
     reverse: True
     filters:
       source_file.kind: html
       is_processable: True

tagger:
  sorter: time
  archives:
    atom:
      source: blog
      target: blog/tags
      template: tag.xml.j2
      extension: xml
    blog:
      source: blog
      target: blog/tags
      template: tag.j2
      extension: html

urlcleaner:
  index_file_names:
    - index.html
  strip_extensions:
    - html

context:
    data:
        site_url: http://45.78.17.153:8080
        site_title: ysh
        blog_title: /dev/blog
        author:
            name: ysh
            url: ""
        google_analytics_id: